on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Build Environment
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install Homebrew
      run: |
        mkdir ~/.homebrew 
        curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C ~/.homebrew
        eval "$(homebrew/bin/brew shellenv)"
        brew update --force --quiet
        chmod -R go-w "$(brew --prefix)/share/zsh"
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - name: Run `nix build`
      run: |
        nix build . 
    - name: Setup Tools
      run: |
        - name: Dapr tool installer
        # You may pin to the exact commit or the version.
        # uses: dapr/setup-dapr@ffde132592c51fcb876dff3925598fd150137569
          uses: dapr/setup-dapr@v1
          with:
            # Version of Dapr CLI to install
            version: # optional, default is 1.2.0


    
